//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.91
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Logging.Logger
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Logging.ResourceData", typeof(ResourceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration key {0} is missing or invalid..
        /// </summary>
        internal static string ConfigurationKeyDoesNotExist {
            get {
                return ResourceManager.GetString("ConfigurationKeyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error writing to the system event log. This error is the result of trying to log a logging exception to the event log.\r\n.
        /// </summary>
        internal static string ErrorWritingToSystemEventLog {
            get {
                return ResourceManager.GetString("ErrorWritingToSystemEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Transport Type {0}.
        /// </summary>
        internal static string InvalidTransportType {
            get {
                return ResourceManager.GetString("InvalidTransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger transport &apos;{0}&apos; failed for LogRecord &apos;{1}&apos;.\r\n.
        /// </summary>
        internal static string LoggerTransportFailed {
            get {
                return ResourceManager.GetString("LoggerTransportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger tried persisting the file to the following location {0} but there were errors. \r\n{1}\r\n.
        /// </summary>
        internal static string LoggerTriedPersistingFile {
            get {
                return ResourceManager.GetString("LoggerTriedPersistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LogRecord was persisted to disk in the following location {0}.
        /// </summary>
        internal static string LogRecordPersistedToDisk {
            get {
                return ResourceManager.GetString("LogRecordPersistedToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration setting {0} does not exist in the configuration file..
        /// </summary>
        internal static string MissingConfigSetting {
            get {
                return ResourceManager.GetString("MissingConfigSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write message to endpoint {0} failed..
        /// </summary>
        internal static string WriteMessageToEndpointFailed {
            get {
                return ResourceManager.GetString("WriteMessageToEndpointFailed", resourceCulture);
            }
        }
    }
}
